Repository wecode-bootcamp-korea/37-2nd-O2bnb-frontend, pull requests merged in 2022-10, with the labels that each got.

#3 [37기 남장현] ADD : Footer.jsx 레이아웃
  .gitignore
  src/components/Footer/Footer.jsx
Labels: 멘토 리뷰 요청

#2 [37기 김효성]Add : Layout 작업중
  package-lock.json
  package.json
  public/data/data.json
  public/image/npay_20.png
  public/image/paycologo.png
  src/Router.js
  src/components/Loading/Loading.js
  src/pages/Payment/NaverPay.js
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Result.js
  src/pages/Payment/SelectCard.js
Labels: Conflict 해결 요청, Rebase 요청

#4 [37기 김대호] ADD : Main
  package-lock.json
  package.json
  public/data/All.json
  public/data/test.json
  public/data/강남구.json
  public/data/마포구.json
  public/data/서초구.json
  public/data/영등포구.json
  public/data/종로구.json
  public/data/중구.json
  public/index.html
  src/pages/Main/FliterModal.jsx
  src/pages/Main/Like.jsx
  src/pages/Main/List.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Map.jsx
  src/pages/Main/MapModal.jsx
  src/pages/Main/Menu.jsx
  src/pages/Payment/NaverPay.js
Labels: Rebase 요청

#5 [37기 이윤승] ADD : 기능 추가
  package-lock.json
  package.json
  public/data/ITEMDETAIL_DATA.json
  public/data/REIVIEW_DATA.json
  public/index.html
  src/pages/ItemDetail/ItemDetail.jsx
  src/pages/ItemDetail/components/Calendar.jsx
  src/pages/ItemDetail/components/InlineCalendar.jsx
  src/pages/ItemDetail/components/ItemDetailHost.jsx
  src/pages/ItemDetail/components/ItemDetailImages.jsx
  src/pages/ItemDetail/components/ItemDetailInfo/ItemDetailInfo.jsx
  src/pages/ItemDetail/components/ItemDetailInfo/components/ItemDetailReservation.jsx
  src/pages/ItemDetail/components/ItemDetailMap.jsx
  src/pages/ItemDetail/components/ItemDetailReview/ItemDetailReview.jsx
  src/pages/ItemDetail/components/ItemDetailTitle.jsx
  src/pages/ItemDetail/components/Modal/AMENITIS_DATA.js
  src/pages/ItemDetail/components/Modal/ModalAmenities.jsx
Labels: Conflict 해결 요청, 수정 요청

#8 [37기 남장현] Nav / Account 기능구현
  public/data/JanghyunData/HOTEL_DATA.json
  public/data/JanghyunData/USER_DATA.json
  src/Router.js
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/component/MenuBox.jsx
  src/components/Nav/component/MenuListBox.jsx
  src/components/Nav/component/SearchBox.jsx
  src/components/Nav/component/User.jsx
  src/components/Nav/component/UserModal.jsx
  src/components/Nav/component/useClickOutside.jsx
  src/pages/Account/Account.jsx
  남장현.zip
Labels: Conflict 해결 요청
